### ISSUE TITLE
mocriのサービス終了に伴う通話サービスの移行先

### ISSUE THREAD

**Issue by YutaGoto** [imas/mokumoku#196]
Discordサーバをたてる？

https://support.mocri.jp/hc/ja/articles/27426806114585

**Comment by YutaGoto** [comment]
3月開催まではmocriを使う予定です。

**Comment by takemikami** [comment]
discordのサーバたてるなら、mokumokuとしてではなくimastudyとしてたててもらえると嬉しいですね
slackだと過去ログ追えないというのもあるので、
